mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('shortener.urls')),

]

mysite/shortener/urls.py
from django.conf.urls import url

from . import views

app_name = "shortener"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<shortcut>[0-9a-zA-Z]+)/$', views.redirect, name='redirect'),
    url(r'^info/(?P<shortcut>[0-9a-zA-Z]+)/$', views.info, name='info'),
    url(r'^shorten$', views.shorten, name="shorten"),

]

mysite/shortener/models.py
from django.db import models
from django.core.validators import URLValidator
import datetime


# Create your models here.

class ShortURL(models.Model):
    shortcut = models.CharField(max_length=16)
    original_url = models.CharField(max_length=256, validators=[URLValidator()])
    pub_date = models.DateTimeField('date published', auto_now=True)#default=datetime.datetime.now())
    times_visited = models.IntegerField(default=0)

    def __str__(self):
        return str(self.shortcut) + ": " + str(self.original_url)

mysite/shortener/forms.py
from django import forms
from .models import ShortURL
import re


class UrlShortenFrom(forms.Form):
    url = forms.URLField(
        label='Paste an url',
        widget=forms.URLInput(attrs={
            'placeholder': 'Link to be shortened',
            'autocomplete': 'off',
        }))

    check = forms.BooleanField(label="Autocorrect URLs", required=False, initial=True)

    custom = forms.CharField(
        label='Your custom shortcut',
        widget=forms.TextInput(attrs={
            'placeholder': '(Optional) your custom shortcut',
            'autocomplete': 'off',
            'maxlength': '16',
        }),
        required=False)

    def clean_custom(self):
        custom = self.cleaned_data['custom']

        if not custom:
            return

        if len(custom) > 16:
            raise forms.ValidationError('Value too long! Shortcut should be max. 16 characters long')

        if not re.match("^[a-zA-Z0-9]+$", custom):
            raise forms.ValidationError('Shortcut can only consist of letters and digits')

        if custom == 'admin':
            raise forms.ValidationError('Sorry, this shortcut is not available')

        try:
            if ShortURL.objects.filter(shortcut=custom).exists():
                raise forms.ValidationError('\'%s\' shortcut already exists.' % custom)
            return custom
        except OverflowError:
            forms.ValidationError('Value too long! Do you really want to shorten your URL ? :)')

mysite/shortener/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponsePermanentRedirect
from .models import ShortURL
from django.views.decorators.http import require_POST, require_GET
import random, string
from .forms import UrlShortenFrom


# Create your views here.

@require_GET
def index(request):
    context = {
        'url_shorten_form': UrlShortenFrom()
    }
    return render(request, 'shortener/index.html', context)


@require_GET
def redirect(request, shortcut):
    try:
        short_url = ShortURL.objects.get(shortcut=shortcut)
        short_url.times_visited += 1
        short_url.save()
        return HttpResponsePermanentRedirect(short_url.original_url)
    except ShortURL.DoesNotExist:
        return render(
            request,
            'shortener/404.html',
            {'error_message': 'Couldn\'t find a link for given shortcut: %s' % shortcut}
        )


@require_GET
def info(request, shortcut):
    try:
        short_url = ShortURL.objects.get(shortcut=shortcut)
        context = {
            'shortcut': short_url.shortcut,
            'original_url': short_url.original_url,
            'pub_date': short_url.pub_date,
            'times_visited': short_url.times_visited,
        }
        return render(request, 'shortener/info.html', context)

    except ShortURL.DoesNotExist:
        return render(
            request,
            'shortener/404.html',
            {'error_message': 'Couldn\'t find a link for given shortcut: %s' % shortcut}
        )


@require_POST
def shorten(request):
    form = UrlShortenFrom(request.POST)
    if form.is_valid():
        url = form.cleaned_data['url']
        custom = form.cleaned_data['custom']
        if custom:
            shortcut = custom
        else:
            shortcut = ''.join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(6))

        shortened_url = ShortURL.objects.create(original_url=url, shortcut=shortcut)

        context = {
            'shortened_url': shortened_url,
            'domain_name': request.META['HTTP_HOST']
        }

        return render(request, 'shortener/success.html', context)
    else:
        return render(request, 'shortener/index.html', {'url_shorten_form': form})

mysite/shortener/templates/shortener/failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Shortened successfully!</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'shortener/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Lato|Raleway" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}"/>
</head>
<body>
<nav><a href="/"><h1><i class="fa fa-home" aria-hidden="true"></i> URLShortener</h1></a></nav>
<div class="outer">
    <div class="middle">
        <div class="inner">
            <p>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            </p>
        </div>
    </div>
</div>

<script src="{% static 'shortener/script.js' %}"></script>
</body>
</html>

mysite/shortener/templates/shortener/form.html
{% if url_shorten_form %}
    <form name="url_shorten_form" action="{% url 'shortener:shorten' %}" method="post">
        {% csrf_token %}
        {{ url_shorten_form.as_p }}
        <button type="submit">Shorten your URL</button>
    </form>
{% endif %}

mysite/shortener/templates/shortener/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>URL shortener</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'shortener/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Lato|Raleway" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}"/>
</head>
<body>
<nav><a href="/"><h1><i class="fa fa-home" aria-hidden="true"></i> URLShortener</h1></a></nav>

<div class="outer">
    <div class="middle">
        <div class="inner">

            {% block submit_form %}
                {% include 'shortener/form.html' %}
            {% endblock %}

        </div>
    </div>
</div>

<script src="{% static 'shortener/script.js' %}"></script>
</body>
</html>

mysite/shortener/templates/shortener/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>URL info</title>
    <link rel="stylesheet" type="text/css" href="{% static 'shortener/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Lato|Raleway" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}"/>
</head>
<body>
<nav><a href="/"><h1><i class="fa fa-home" aria-hidden="true"></i> URLShortener</h1></a></nav>
<div class="outer">
    <div class="middle">
        <div class="inner">
            <h1>Link information</h1>
            <div><span>Shortcut: </span><span>{{ shortcut }}</span></div>
            <div><span>Original URL: </span><span><a href="{{ original_url }}">{{ original_url }}</a></span></div>
            <div><span>Date published: </span><span>{{ pub_date }}</span></div>
            <div><span>Times visited: </span><span>{{ times_visited }}</span></div>
        </div>
    </div>
</div>
</body>
</html>

mysite/shortener/templates/shortener/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Shortened successfully!</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'shortener/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Lato|Raleway" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}"/>
</head>
<body>
<nav><a href="/"><h1><i class="fa fa-home" aria-hidden="true"></i> URLShortener</h1></a></nav>
<div class="outer">
    <div class="middle">
        <div class="inner">
            <p>
                <label for="id_shortlink">Your new, short URL:</label>
                <input type="text" name="shortlink" id="id_shortlink" value="http://{{ domain_name }}{% url 'shortener:redirect' shortened_url.shortcut %}"/>
                <button type="button" class="shortlink-copy">Copy to clipboard</button>

                <label for="id_linkinfo">You can check information about this link at :</label>
                <input type="text" name="linkinfo" id="id_linkinfo" value="http://{{ domain_name }}{% url 'shortener:info' shortened_url.shortcut %}"/>
                <button type="button" class="linkinfo-copy">Copy to clipboard</button>
            </p>
        </div>
    </div>
</div>

<script src="{% static 'shortener/script.js' %}"></script>
</body>
</html>